cookie:
  expiry_days: 1
  key: signature_key
  name: user_cookie
credentials:
  usernames:
    andipetualang:
      name: andi
      password: $2b$12$3/5U9Yo3MKjXTpxLrB/j/OETMMH.ZIBelW/60yHFxjrY5F.tHoq0C
      role: taksonom lapangan
    masden:
      name: Mas Den
      password: $2b$12$FjpQAHy1OTm9av5fe/wI9O43dFmXoGMyc0.pVLYcjrSrKr7f/WXHS
      role: admin
    udin:
      name: Udin
      password: $2b$12$FjpQAHy1OTm9av5fe/wI9O43dFmXoGMyc0.pVLYcjrSrKr7f/WXHS
      role: pengembang model
